SET SCHEMA blog;

INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('HOME', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('ABOUT', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('TECH', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Docker', SELECT ID FROM CATEGORY WHERE NAME='TECH');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Engine', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Compose', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Swarm', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('MOVIE', NULL);
