SET SCHEMA blog;

INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('HOME', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('ABOUT', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('TECH', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Spring', SELECT ID FROM CATEGORY WHERE NAME='TECH');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Spring Data', SELECT ID FROM CATEGORY WHERE NAME='Spring');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Spring Security', SELECT ID FROM CATEGORY WHERE NAME='Spring');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Docker', SELECT ID FROM CATEGORY WHERE NAME='TECH');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Engine', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Compose', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Swarm', SELECT ID FROM CATEGORY WHERE NAME='Docker');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Database', SELECT ID FROM CATEGORY WHERE NAME='TECH');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('MariaDB', SELECT ID FROM CATEGORY WHERE NAME='Database');
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('MOVIE', NULL);

INSERT INTO ARTICLE (TITLE, CONTENTS, IS_DRAFT, CREATED_AT, UPDATED_AT, CATEGORY_ID)
VALUES('MariaDB Duplication', 'not write', false, now(), now(), SELECT ID FROM CATEGORY WHERE NAME='MariaDB');