INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('Subjects', NULL);
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('HOME', (SELECT ID FROM CATEGORY WHERE NAME = 'Subjects'));
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('ABOUT', (SELECT ID FROM CATEGORY WHERE NAME = 'Subjects'));
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('TECH', (SELECT ID FROM CATEGORY WHERE NAME = 'Subjects'));
INSERT INTO CATEGORY (NAME, PARENT_ID) VALUES ('MOVIE', (SELECT ID FROM CATEGORY WHERE NAME = 'Subjects'));
